const ContactsActionTypes = {
  LOADING_CONTACTS_START: 'LOADING_CONTACTS_START',
  LOADING_CONTACTS_SUCCESS: 'LOADING_CONTACTS_SUCCESS',
  LOADING_CONTACTS_FAILURE: 'LOADING_CONTACTS_FAILURE',
  DELETING_CONTACTS_START: 'DELETING_CONTACTS_START',
  DELETING_CONTACTS_SUCCESS: 'DELETING_CONTACTS_SUCCESS',
  DELETING_CONTACTS_FAILURE: 'DELETING_CONTACTS_FAILURE',
  ADD_SELECTED_CONTACT: 'ADD_SELECTED_CONTACT',
  REMOVE_SELECTED_CONTACT: 'REMOVE_SELECTED_CONTACT',
  SELECT_ALL_CONTACTS: 'SELECT_ALL_CONTACTS',
  UNSELECT_ALL_CONTACTS: 'UNSELECT_ALL_CONTACTS',
  UNSELECT_CONTACTS_BY_IDS: 'UNSELECT_CONTACTS_BY_IDS',
  ADD_CONTACT_TO_EDIT: 'ADD_CONTACT_TO_EDIT',
  ADD_CONTACT_START: 'ADD_CONTACT_START',
  ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
  ADD_CONTACT_FAILURE: 'ADD_CONTACT_FAILURE',
  UPDATE_CONTACT_START: 'UPDATE_CONTACT_START',
  UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
  UPDATE_CONTACT_FAILURE: 'UPDATE_CONTACT_FAILURE',
  IMPORT_CONTACTS_START: 'IMPORT_CONTACTS_START',
  IMPORT_CONTACTS_SUCCESS: 'IMPORT_CONTACTS_SUCCESS',
  IMPORT_CONTACTS_FAILURE: 'IMPORT_CONTACTS_FAILURE',
  EXPORT_ALL_CONTACTS_START: 'EXPORT_ALL_CONTACTS_START',
  EXPORT_ALL_CONTACTS_SUCCESS: 'EXPORT_ALL_CONTACTS_SUCCESS',
  EXPORT_ALL_CONTACTS_FAILURE: 'EXPORT_ALL_CONTACTS_FAILURE'
};

export default ContactsActionTypes;
